<?php

namespace DR\NewsBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLike($pattern="main_",$table='category',$start=true)
	{
		$queryBuilder = $this->createQueryBuilder('n');
		$queryBuilder->where('n.' . $table . ' LIKE :pattern');
		if ($start)
			$queryBuilder->setParameter('pattern', $pattern . '%');
		else
			$queryBuilder->setParameter('pattern', '%' . $pattern );
		
		$queryBuilder->orderBy('n.date', 'ASC');
		return 
			$queryBuilder->getQuery()
						->getResult();
		
	}
}
