#dr_user:
#    resource: "@DRUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

dr_news:
    resource: "@DRNewsBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile