<?php

namespace DR\ImageBundle\Repository;

/**
 * ImageContRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageContRepository extends \Doctrine\ORM\EntityRepository
{
}
